### ISSUE TITLE
Request: updates to API docs

### ISSUE THREAD

**Issue by jcass77** [PromyLOPh/pandora-apidoc#11]
I had a look at the *ads* branch of pianobar for examples of how to implement ad-handling support in pydora and Mopidy-Pandora.

It's working fairly well and I was wondering if you have any other insights that are not reflected in the API documentation yet?

https://github.com/PromyLOPh/pianobar/commit/fbfc5f1d5508533454187171024625ec05daa88d lists a bunch of additional parameters to the JSON calls that I have not heard of before, and don't know how to use.

Examples include ```includeAdvertiserAttributes```, ```xplatformAdCapable```, ```includeShuffleInsteadOfQuickMix```, and ```includeCompletePlaylist```, among others.

**Comment by jcass77** [comment]
...maybe this question should be:is there an easy way to include a sample of the JSON response for each optional parameter to better understand the effect it has?

**Comment by PromyLOPh** [comment]
> I was wondering if you have any other insights that are not reflected
> in the API documentation yet?
Unfortunately no. I only looked briefly at the Android client and
implemented it (hopefully) the same way.

> https://githubcom/PromyLOPh/pianobar/commit/fbfc5f1d5508533454187171024625ec05daa88d
> lists a bunch of additional parameters to the JSON calls that I have
> not heard of before, and don't know how to use
> 
> Examples include ```includeAdvertiserAttributes```,
> ```xplatformAdCapable```, ```includeShuffleInsteadOfQuickMix```, and
> ```includeCompletePlaylist```, among others 
I don’t know either. These are parameters the official Android client
sends.  They’re not required though, which is why I did not bother to
document them yet.

> ...maybe this question should be:is there an easy way to include a
> sample of the JSON response for each optional parameter to better
> understand the effect it has?
There’s no secret documentation in my back pocket that I can pull out ;)
If you want to know what the switches do then you’ll have to go through
them one by one and look at Pandora’s response. Please share the results
if you decide to do that.

**Comment by jcass77** [comment]
This has been addressed in https://github.com/PromyLOPh/pandora-apidoc/pull/12.
